### PR TITLE
Update comparison_with_webpacker.md

### PR DESCRIPTION
**Pull request by justin808**
Address feedback in https://github.com/rails/jsbundling-rails/issues/78

### CODE REVIEW

**Comment by justin808** [comment]
@dhh can you let me know if this helps or if you'd like some changes here.

**Comment by justin808** [comment]
Any chance of getting a review?

**Comment by justin808** [comment]
Can I get a review?

**Comment by hachi8833** [comment]
I've been waiting for the merging 🙏

**Comment by justin808** [comment]
Hi @rafaelfranca @dhh, is there anything that you'd like changed?

**Pull request merged**
