### PR TITLE
Configure Basic Testing / CI

### PR DESCRIPTION
**Pull request by ksylvest**
Some recent changes to how assets are built proved challenging no tests are run on this project. To fix, proposing some basic tests using selenium / capybara / minitest. I'm unsure on the how to confirm GitHub Actions (might be repo setting?), but locally the following works:

```bash
cd test/dummy && rake test:prepare
```

```bash
bin/test
```

Ideally this CI might use a matrix to test with bun / yarn / NPM. For now the default bun option is used. If maintainers are interested, the full matrix of tests are fairly easy in a followup.

### CODE REVIEW

**Comment by zzak** [comment]
Hey, I was just here to do the same, except I don't think we should use the dummy app pattern. It's a thing we're trying to get rid of in Rails, and I will open a PR to add something similar to this project.

**Comment by ksylvest** [comment]
Hey @zzak - thanks for commenting. I'm happy to nuke the dummy app. Do you have a link to a project configured the correct way?

**Comment by ksylvest** [comment]
NVM - think I found (https://github.com/rails/rails/pull/50427/commits/2fd5dc9473301a7ed3f01261b348ca015c6a28ad)...

I've split the core testing setup to this PR: https://github.com/rails/jsbundling-rails/pull/186

I can then check through introducing an actual test if you are OK with the other PR and close this.

**Comment by zzak** [comment]
@ksylvest Yeah, I'm not sure we need to send so many PRs until we have something meaty enough to merge. Happy to collaborate on this, and to avoid any back&forth feel free to reach out on discord (`__zzak__`) or `@` me in the [Rails discord](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#get-some-feedback).

**Pull request closed without merging**
