### PR TITLE
Use `overmind` to run Procfiles, if available

### PR DESCRIPTION
**Pull request by MatheusRich**
[Overmind] is a process manager (like foreman) for Procfile-based applications. The advantage is that it [allows to use debuggers] like pry or `binding.irb` without installing extra gems.

---

This PR is very simple, as I'm waiting for feedback on whether the maintainers like this idea. I can add tests and a CHANGELOG entry after that. I'll also open a PR on cssbundling-rails if this one is accepted.

[Overmind]: https://github.com/DarthSim/overmind
[allows to use debuggers]: https://heyvaleria.github.io/coding/2022/04/27/overmind.html

### CODE REVIEW

**Comment by MatheusRich** [comment]
@dhh thoughts?

**Comment by dhh** [comment]
I don't think it's worth carrying this specialization. You can just tweak it yourself after it's setup.

**Comment by semaperepelitsa** [comment]
Is there any reason to prefer Foreman vs Overmind?

**Comment by MatheusRich** [comment]
@semaperepelitsa I believe foreman is prefered because it's a pury-ruby solution. You can just `gem install` it without worrying about OSes and other packages.

**Comment by glaucocustodio** [comment]
Foreman has this [annoying issue](https://github.com/ddollar/foreman/pull/780), its fork [overman](https://github.com/spinels/overman/) addresses that. Would you accept a PR for that @dhh?

**Pull request closed without merging**
